import "@/styles/globals.css";
import type { Metadata } from "next";
import { quicksand } from "@/styles/fonts";

import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Flowspark - Digital Marketing Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased`}>
        <main className="dark:bg-neutral-800 dark:text-white">{children}</main>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
